# Appendices {.unnumbered}

## Appendix 1 - New Worker Orientation {.unnumbered}

## Appendix 2 - Tailboard Template {.unnumbered}

**Project: Location : Date:**

  ------------------------------------------------------------------------
  **Name**                    **Crew             **Signature**
                              Leader/Member**    
  --------------------------- ------------------ -------------------------
                              Leader Member      

                              Leader Member      

                              Leader Member      

                              Leader Member      
  ------------------------------------------------------------------------

**Pre-existing Health Conditions?**

**Description of work: (ex. Culvert assessments, electrofishing, water
sampling, redd surveys, RPAS surveys etc.)**

**Site Conditions:**

  --------------------------------------------------------------------------
  Clear              Dry               Hot             Cloudy/Broken     
  ------------- ---- ------------ ---- ---------- ---- ----------------- ---
  Raining            Wet               Warm            Foggy             

  Snowing            Muddy             Cold            Icy/Snow Covered  
  --------------------------------------------------------------------------

**Site Risks and Hazards. Job risks:**

  -----------------------------------------------------------------------------------------------
  Wildlife           Slippery and/or uneven        Chainsaw/knife/loppers (cuts)              
                     ground                                                                   
  ------------- ---- ------------------------- --- ------------------------------------------ ---
  Swiftwater         Exposure (heat/cold)          Electric Shock (electrofisher)             

  Remote             Machinery                     Open water                                 
  worksite                                                                                    

  Traffic            ATV/Sled (roll                Overhead Snags                             
                     over/burns/collision)                                                    

  Bush roads         Chemicals                     Sharp shrubs (eye injury)                  

  Dogs               Helicopters (rotors,          Other                                      
                     lines, stranding)             \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   
  -----------------------------------------------------------------------------------------------

**Plans Reviewed:**

  ------------------------------------------------------------------------
  Emergency Response Plan            Field Safety Plan **(Call in /    
                                     Call out Procedures)**            
  ------------------------------ --- --------------------------------- ---
  Safe Work Procedures               Roles and Responsibilities        

  ------------------------------------------------------------------------

**Personal Protective Equipment Checklist/Inspection:**

  --------------------------------------------------------------------------------------------------------------
  Hi-Vis Vest            Protective footwear (**assess** **condition)**                      Throw Bag       
  ------------------ --- --------------------------------------------------------------- --- --------------- ---
  Cell phones /          Hard Hat                                                            PFD             
  radio / spot                                                                                               

  Waders / **Wading      Water/ Food supplies                                                Dry Suit        
  Belt**                                                                                                     

  Bear Spray/Bangers     Rainwear/ Weather Wear (extra coat)                                 Linesman Gloves 

  Level 1/ Personal      Other\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_       Whistle         
  FA Kit                                                                                                     
  --------------------------------------------------------------------------------------------------------------

**Machinery Inspection (Vehicle/Trailer/ATV)** Vehicle
ID\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

  --------------------------------------------------------------------------
  Obvious damage/leaks            Horn                                   
  ----------------------- --- --- --------------------------------- ---- ---
  Tires                           Brakes                                 

  Headlights / tail               Parking Brake                          
  lights / Signals                                                       

  Fuel                            Uneven tire wear/rough steering?       

  Oil Level                       Safety/Emergency information           

  Radiator fluid                  Spare Tire/ Jack                       

  Windshield fluid                Suspension/Steering                    

  okay                       X   needs attention                       X
  --------------------------------------------------------------------------

**Housekeeping for Slips, Trips and Fall Prevention:**

  --------------------------------------------------------------------------
  Slippery/uneven         Spills              Unsecured mats, tiles,     
  ground                                      carpets                    
  ------------------ ---- -------------- ---- -------------------------- ---
  Loose debris            Cables/cords        Smoke/Steam/Fog view       
                                              obstruction                

  Poor lighting           Barriers in         Good footwear              
                          place                                          
  --------------------------------------------------------------------------

**Types of injuries that could occur:**

  --------------------------------------------------------------------------------
  Sprains/breaks/bruises        Crush injuries      Electrocution              
  ------------------------ ---- -------------- ---- -------------------------- ---
  Cuts/lacerations              Head injuries       Traffic accident related   

  Drowning                      Exposure            Repetitive Strain          
                                                    (eg.tendonitis)            
  --------------------------------------------------------------------------------

**Barriers to first aid being provided to injured worker:**

  -----------------------------------------------------------------------------------------------------------------
  Unsafe Accident Scene              Victim/ Attendant Panic and/or Shock                                       
  ------------------------------- -- -------------------------------------------------------------------------- ---
  Remote worksite (distance to       Time to get Level 1 kit from vehicle if required                           
  Hospital/Vehicle)                                                                                             

  Slippery / Steep and/or uneven     Other                                                                      
  ground                             \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   
  -----------------------------------------------------------------------------------------------------------------

**First Aid Assessment (Check one) -- See Appendix 8 of H&S Plan for
details/lower requirement scenarios**

  -----------------------------------------------------------------------
  **Scenario**                      **Requirement**
  --------------------------------- -------------------------------------
  \<6 -- 30 workers and \> 20       Level 1 Certificate and Level 1 Kit
  minutes from hospital and "low"   
  risk of injury                    

  6 -- 15 workers and \> 20 minutes Level 1 Certificate, Level 1 Kit,
  from hospital and "moderate" risk Transportation endorsement and ETV
  of injury                         equipment

  6 -- 10 workers and \> 20 minutes Level 1 Certificate, Level 1 Kit,
  from hospital and "high" risk of  Transportation endorsement and ETV
  injury                            equipment

  11 -- 30 workers and \> 20        Level 3 Certificate, Level 3 Kit,
  minutes from hospital and "high"  dressing station and ETV
  risk of injury                    
  -----------------------------------------------------------------------

**Discuss incidents and close calls in past similar work (reasons for
incident/close call and corrective actions taken/to be taken to avoid
similar situations).**

**Discuss Relevant Industry Alerts:**

  --------------------------------------------------------------------------
  Overhead hazards             Secure contents in       Bears            
  (snags/branches)             vehicles                                  
  ------------------------ --- -------------------- --- ---------------- ---
  Winter Driving               Alert while Driving      Vehicle          
  Preparation                                           Maintenance      

  Unstable machinery           Floods and               Devils Club in   
                               Landslides               eyes             
  --------------------------------------------------------------------------

**Additional Safety Comments:**

**Worker Assessment** Worker:
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_Assessed by:
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

  ------------------------------------------------------------------------
  Can identify worksite hazards      Wears hard hat / protection    
  ------------------------------ --- ------------------------------ ------
  Is alert and focused on job        Uses required hearing          
                                     protection                     

  Demonstrates safe use of tools     Wears high visibility /        
  & equip.                           protective clothing            

  Demonstrates proper use of         Wears appropriate footwear for 
  seat belt                          job                            

  Has required license /             Wears wading belt / bear spray 
  certificate(s)                                                    

  **Worker is Competent**                                           
  ------------------------------------------------------------------------

Feedback:
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Signatures: Worker:
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_Assessed by:
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

**Call In/Call out Numbers**

+----------+--------------------+-------------+----------------------+
| **Crew   |                    | **Personal  | **Personal Emergency |
| Member** |                    | Emergency   | Contact \#**         |
|          |                    | Contact**   |                      |
+==========+====================+=============+======================+
| Allan    | 250 777 1518       | Tara Stark  | 250 352 5311 Cell:   |
| Irvine   |                    |             | 250 505 9489         |
+----------+--------------------+-------------+----------------------+
|          |                    |             |                      |
+----------+--------------------+-------------+----------------------+
|          |                    |             |                      |
+----------+--------------------+-------------+----------------------+
| Inreach  | 226 241 6177       |             |                      |
| text     |                    |             |                      |
| (al)     | allanirvine75@     |             |                      |
|          | inreach.garmin.com |             |                      |
+----------+--------------------+-------------+----------------------+

**Emergency Contact Info:**

  ----------------------------------------------------------------------------------------------
                  **Kaslo**   **Grand    **Nelson**   **Fernie**   **Creston**   **Mackenzie**
                              Forks**                                            
  --------------- ----------- ---------- ------------ ------------ ------------- ---------------
  RCMP            911         911        911          911          911           911
  Search&Rescue                                                                  

  Hospital        250 353     250        250 352-3111 250 423 4453 250 428 2286  2509973263
                  2225        443-2100                                           

  Poison Control  1 800 567                                                      
                  8911                                                           
  ----------------------------------------------------------------------------------------------

\(250\) 565-2000 Prince George Hospital

**[Report All Incidents and Close Calls on Incident/Close Call Reporting
Form In Safety Binders in Vehicles]{.underline}**

## Appendix 3 - First Aid Requirements {.unnumbered}

**Table 1**: This table applies to a workplace that an employer
determines under section 3.16 (2) (b) of the Regulation creates a low
risk of injury and that is more than 20 minutes surface travel time away
from a hospital.

+------------+------------+------------+------------+------------+
| **Item**   | **Column   | **Column   | **Column   | **Column   |
|            | 1\         | 2\         | 3\         | 4\         |
|            | Number of  | Supplies,  | Level of   | Transp     |
|            | workers    | equipment, | first aid  | ortation** |
|            | per        | and        | c          |            |
|            | shift**    | facility** | ertificate |            |
|            |            |            | for        |            |
|            |            |            | a          |            |
|            |            |            | ttendant** |            |
+============+============+============+============+============+
| 1          | 1          | Personal   |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 2          | 2-5        | Basic      |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 3          | 6-30       | Level 1    | Level 1    |            |
|            |            | first aid  | certificate|            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 4          | 31-50      | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            | with Tr    |            |
|            |            | -   ETV    | an         |            |
|            |            |            | sportation |            |
|            |            | equipment  | E          |            |
|            |            |            | ndorsement |            |
+------------+------------+------------+------------+------------+
| 5          | 51-75      | Level 3    | Level 3    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            |   Dressing |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |    station |            |            |
|            |            |            |            |            |
|            |            | ETV        |            |            |
|            |            | equipment  |            |            |
+------------+------------+------------+------------+------------+
| 6          | 76 or more | Level 3    | Level 3    | ETV        |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
|            |            |            |            |            |
|            |            | ETV        |            |            |
|            |            | equipment  |            |            |
+------------+------------+------------+------------+------------+

**Table 2**: This table applies to a workplace that an employer
determines under section 3.16 (2) (b) of the Regulation creates a low
risk of injury and that is 20 minutes or less surface travel time away
from a hospital.

+------------+------------+------------+------------+------------+
| **It em**  | **Column   | **Column   | **Column   | **Column   |
|            | 1\         | 2\         | 3\         | 4\         |
|            | Number of  | Supplies,  | Level of   | Transp     |
|            | workers    | equipment, | first aid  | ortation** |
|            | per        | and        | c          |            |
|            | shift**    | facility** | ertificate |            |
|            |            |            | for        |            |
|            |            |            | a          |            |
|            |            |            | ttendant** |            |
+============+============+============+============+============+
| 1          | 1          |            |            |            |
+------------+------------+------------+------------+------------+
| 2          | 2-10       | Basic      |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 3          | 11-50      | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
+------------+------------+------------+------------+------------+
| 4          | 51-100     | Level 2    | \*Level 2  |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            |   Dressing |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |    station |            |            |
+------------+------------+------------+------------+------------+
| 5          | 101 or     | Level 2    | \*Level 2  |            |
|            | more       | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
+------------+------------+------------+------------+------------+

**Table 3**: This table applies to a workplace that an employer
determines under section 3.16 (2) (b) of the Regulation creates a
moderate risk of injury and that is more than 20 minutes surface travel
time away from a hospital.

+------------+------------+------------+------------+------------+
| **It em**  | **Column   | **Column   | **Column   | **Column   |
|            | 1\         | 2\         | 3\         | 4\         |
|            | Number of  | Supplies,  | Level of   | Transp     |
|            | workers    | equipment, | first aid  | ortation** |
|            | per        | and        | c          |            |
|            | shift**    | facility** | ertificate |            |
|            |            |            | for        |            |
|            |            |            | a          |            |
|            |            |            | ttendant** |            |
+============+============+============+============+============+
| 1          | 1          | Personal   |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 2          | 2-5        | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
+------------+------------+------------+------------+------------+
| 3          | 6-15       | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            | with Tr    |            |
|            |            | -   ETV    | an         |            |
|            |            |            | sportation |            |
|            |            | equipment  | E          |            |
|            |            |            | ndorsement |            |
+------------+------------+------------+------------+------------+
| 4          | 16-50      | Level 3    | Level 3    |  ETV       |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            |   Dressing |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |    station |            |            |
|            |            |            |            |            |
|            |            | -   ETV    |            |            |
|            |            |            |            |            |
|            |            | equipment  |            |            |
+------------+------------+------------+------------+------------+
| 5          | 51-100     | Level 3    | Level 3    |  ETV       |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
|            |            |            |            |            |
|            |            | -   ETV    |            |            |
|            |            |            |            |            |
|            |            | equipment  |            |            |
+------------+------------+------------+------------+------------+
| 6          | 101-300    | Level 3    | Level 3    | Industrial |
|            |            | first aid  | c          | ambulance  |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            | Industrial |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  ambulance |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  equipment |            |            |
+------------+------------+------------+------------+------------+
| 7          | 301 or     | Level 3    | 2          | Industrial |
|            | more       | first aid  | a          | ambulance  |
|            |            | kit        | ttendants, |            |
|            |            |            | each with  |            |
|            |            | -   First  | Level 3    |            |
|            |            |     aid    | ce         |            |
|            |            |     room   | rtificates |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            | Industrial |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  ambulance |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  equipment |            |            |
+------------+------------+------------+------------+------------+

**Table 4**: This table applies to a workplace that an employer
determines under section 3.16 (2) (b) of the Regulation creates a
moderate risk of injury and that is 20 minutes or less surface travel
time away from a hospital.

+------------+------------+------------+------------+------------+
| **It em**  | **Column   | **Column   | **Column   | **Column   |
|            | 1\         | 2\         | 3\         | 4\         |
|            | Number of  | Supplies,  | Level of   | Transp     |
|            | workers    | equipment, | first aid  | ortation** |
|            | per        | and        | c          |            |
|            | shift**    | facility** | ertificate |            |
|            |            |            | for        |            |
|            |            |            | a          |            |
|            |            |            | ttendant** |            |
+============+============+============+============+============+
| 1          | 1          | Personal   |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 2          | 2-5        | Basic      |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 3          | 6-25       | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
+------------+------------+------------+------------+------------+
| 4          | 26-75      | Level 2    | \*Level 2  |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            |   Dressing |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |    station |            |            |
+------------+------------+------------+------------+------------+
| 5          | 76 or more | Level 2    | \*Level 2  |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
+------------+------------+------------+------------+------------+

**Table 5**: This table applies to a workplace that an employer
determines under section 3.16 (2) (b) of the Regulation creates a high
risk of injury and that is more than 20 minutes surface travel time away
from a hospital.

+------------+------------+------------+------------+------------+
| **It em**  | **Column   | **Column   | **Column   | **Column   |
|            | 1\         | 2\         | 3\         | 4\         |
|            | Number of  | Supplies,  | Level of   | Transp     |
|            | workers    | equipment, | first aid  | ortation** |
|            | per        | and        | c          |            |
|            | shift**    | facility** | ertificate |            |
|            |            |            | for        |            |
|            |            |            | a          |            |
|            |            |            | ttendant** |            |
+============+============+============+============+============+
| 1          | 1          | Personal   |            |            |
|            |            | first aid  |            |            |
|            |            | kit        |            |            |
+------------+------------+------------+------------+------------+
| 2          | 2-5        | Level 1    | Level 1    |            |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
+------------+------------+------------+------------+------------+
| 3          | 6-10       | Level 1    | Level 1    |  ETV       |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            | with Tr    |            |
|            |            | -   ETV    | an         |            |
|            |            |            | sportation |            |
|            |            | equipment  | E          |            |
|            |            |            | ndorsement |            |
+------------+------------+------------+------------+------------+
| 4          | 11-30      | Level 3    | Level 3    |  ETV       |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            |   Dressing |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |    station |            |            |
+------------+------------+------------+------------+------------+
| 5          | 31-50      | Level 3    | Level 3    |  ETV       |
|            |            | first aid  | c          |            |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
|            |            |            |            |            |
|            |            | -   ETV    |            |            |
|            |            |            |            |            |
|            |            | equipment  |            |            |
+------------+------------+------------+------------+------------+
| 6          | 51-200     | Level 3    | Level 3    | Industrial |
|            |            | first aid  | c          | ambulance  |
|            |            | kit        | ertificate |            |
|            |            |            |            |            |
|            |            | -   First  |            |            |
|            |            |     aid    |            |            |
|            |            |     room   |            |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            | Industrial |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  ambulance |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  equipment |            |            |
+------------+------------+------------+------------+------------+
| 7          | 201 or     | Level 3    | 2          | Industrial |
|            | more       | first aid  | a          | ambulance  |
|            |            | kit        | ttendants, |            |
|            |            |            | each with  |            |
|            |            | -   First  | Level 3    |            |
|            |            |     aid    | ce         |            |
|            |            |     room   | rtificates |            |
|            |            |            |            |            |
|            |            | -          |            |            |
|            |            | Industrial |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  ambulance |            |            |
|            |            |            |            |            |
|            |            |            |            |            |
|            |            |  equipment |            |            |
+------------+------------+------------+------------+------------+

## Appendix 4 - Incidence/Close Call Template {.unnumbered}

> Date of Incident: Company:
>
> Date Reported: Location:
>
> Reported By: Type of Job:

+-----------------------------------------------+---+------------------+
| > **Describe incident / close call**          | > | > **Category**   |
| >                                             |   |                  |
| > **(draw diagram on other side if helpful)** | * |                  |
|                                               | * |                  |
|                                               | ☑ |                  |
|                                               | * |                  |
|                                               | * |                  |
+===============================================+===+==================+
| > Notes:                                      |   | > close call     |
+-----------------------------------------------+---+------------------+
|                                               |   | > bodily         |
|                                               |   | > injury/illness |
+-----------------------------------------------+---+------------------+
| > Notes:                                      |   | > lost time      |
+-----------------------------------------------+---+------------------+
|                                               |   | > dangerous      |
|                                               |   | > goods spill    |
+-----------------------------------------------+---+------------------+
| > Notes:                                      |   | > fire           |
+-----------------------------------------------+---+------------------+
|                                               |   | > vehicle        |
|                                               |   | > incident /     |
|                                               |   | > damage         |
+-----------------------------------------------+---+------------------+
| > Notes:                                      |   | > ATV incident / |
|                                               |   | > damage         |
+-----------------------------------------------+---+------------------+
|                                               |   | > other          |
|                                               |   | > equipment      |
|                                               |   | > damage         |
+-----------------------------------------------+---+------------------+
| > Notes:                                      |   | > other          |
|                                               |   | > (describe)     |
+-----------------------------------------------+---+------------------+
|                                               |   | > other          |
|                                               |   | > (describe)     |
+-----------------------------------------------+---+------------------+
| > Names/contact info of any individual or     |   |                  |
| > witnesses involved in incident / close      |   |                  |
| > call:                                       |   |                  |
+-----------------------------------------------+---+------------------+
| > If first aid was rendered, name of          |   |                  |
| > attendant:                                  |   |                  |
+-----------------------------------------------+---+------------------+

+----------------------+---+-----------------+---+---------------------+
| > **Describe         |   |                 |   |                     |
| > immediate and root |   |                 |   |                     |
| > cause of incident  |   |                 |   |                     |
| > / close call:**    |   |                 |   |                     |
+======================+===+=================+===+=====================+
| > **Notes**          | > | > **Immediate   | > | > **Root cause(s)** |
|                      |   | > cause(s)**    |   |                     |
|                      | * |                 | * |                     |
|                      | * |                 | * |                     |
|                      | ☑ |                 | ☑ |                     |
|                      | * |                 | * |                     |
|                      | * |                 | * |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > failure to    |   | > inadequate work   |
|                      |   | > follow safe   |   | > planning,         |
|                      |   | > work          |   | > engineering,      |
|                      |   | > procedures    |   | > design            |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > improper use  |   | > inadequate        |
|                      |   | > of            |   | > polices,          |
|                      |   | > equipmen      |   | > procedures        |
|                      |   | t/tools/lockout |   |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > failure to    |   | > inadequate        |
|                      |   | > warn or       |   | > communications    |
|                      |   | > instruct      |   |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > body motions  |   | > inadequate        |
|                      |   | > -- pushing,   |   | > supervision       |
|                      |   | > pulling       |   |                     |
|                      |   | > repetition    |   |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > improper use  |   | > inadequate        |
|                      |   | > of PPE        |   | > risk/hazard       |
|                      |   |                 |   | > assessment        |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > inadequate    |   | > mental, physical  |
|                      |   | > awareness of  |   | > stress/fatigue    |
|                      |   | > surroundings  |   |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > poor          |   | > inadequate        |
|                      |   | > housekeeping  |   | > main              |
|                      |   |                 |   | tenance/inspections |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > worksite      |   | > inadequate        |
|                      |   | > conditions -- |   | > physical          |
|                      |   | > weather       |   | > abilities         |
|                      |   | > congestion,   |   |                     |
|                      |   | > layout,       |   |                     |
|                      |   | > (circle)      |   |                     |
+----------------------+---+-----------------+---+---------------------+
| > Notes:             |   | > other         |   | > other             |
+----------------------+---+-----------------+---+---------------------+

+------------------------------+---------------------------------------+
| > **Describe corrective      |                                       |
| > action(s) to be            |                                       |
| > undertaken:**              |                                       |
+==============================+=======================================+
|                              |                                       |
+------------------------------+---------------------------------------+
|                              |                                       |
+------------------------------+---------------------------------------+
|                              |                                       |
+------------------------------+---------------------------------------+
|                              |                                       |
+------------------------------+---------------------------------------+
|                              |                                       |
+------------------------------+---------------------------------------+
| > Person responsible for     |                                       |
| > corrective action:         |                                       |
+------------------------------+---------------------------------------+
| > Date action to be          |                                       |
| > completed by:              |                                       |
+------------------------------+---------------------------------------+
| > Person responsible to sign |                                       |
| > here when completed:       |                                       |
+------------------------------+---------------------------------------+
| > Date when action was       |                                       |
| > completed:                 |                                       |
+------------------------------+---------------------------------------+

> **Report and actions reviewed by**
>
> **SEND A COPY OF THIS REPORT TO THE PARTY YOU REPORT TO.**


## Appendix 5 - Contractor Selection and Safety Checklist {.unnumbered}

**Contractor Selection Form**



**Contractor Safety Checklist**

To be completed at the commencement of activities at the start of the
year and then on a quarterly basis thereafter.

+---------------+-----------------+---------------+---------------+
|               |                 | **Contractor  |               |
| **            |                 | Contact:**    |               |
| Contractor:** |                 |               |               |
+:==============+=================+:==============+===============+
| **Location:** |                 | **Date:**     |               |
+---------------+-----------------+---------------+---------------+

+---------------+-----------+-----------+-----------+-----------+
| **Item**      |           | -   \*Ye  | **No**    | **Co      |
|               |           |           |           | mments**  |
|               |           | s\*\*     |           |           |
+===============+===========+===========+===========+===========+
| ***Will a     |           |           |           |           |
| qualified     |           |           |           |           |
| supervisor    |           |           |           |           |
| who meets the |           |           |           |           |
| criteria      |           |           |           |           |
| below be on   |           |           |           |           |
| site at all   |           |           |           |           |
| times?***     |           |           |           |           |
|               |           |           |           |           |
| ***Qualified  |           |           |           |           |
| S             |           |           |           |           |
| upervision*** |           |           |           |           |
| means a       |           |           |           |           |
| person who    |           |           |           |           |
| instructs,    |           |           |           |           |
| directs and   |           |           |           |           |
| controls      |           |           |           |           |
| workers in    |           |           |           |           |
| the           |           |           |           |           |
| performance   |           |           |           |           |
| of their      |           |           |           |           |
| duties and    |           |           |           |           |
| who is        |           |           |           |           |
| knowledgeable |           |           |           |           |
| of the work,  |           |           |           |           |
| the hazards   |           |           |           |           |
| involved and  |           |           |           |           |
| the means to  |           |           |           |           |
| control the   |           |           |           |           |
| hazards, by   |           |           |           |           |
| reason of     |           |           |           |           |
| education,    |           |           |           |           |
| training,     |           |           |           |           |
| experience or |           |           |           |           |
| a combination |           |           |           |           |
| thereof.      |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| How is your   |           |           |           |           |
| organization  |           |           |           |           |
| identifying   |           |           |           |           |
| and           |           |           |           |           |
| communicating |           |           |           |           |
| hazards in    |           |           |           |           |
| the           |           |           |           |           |
| workplace?    |           |           |           |           |
| documentation |           |           |           |           |
| required      |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What does     |           |           |           |           |
| your          |           |           |           |           |
| organization  |           |           |           |           |
| pre-work      |           |           |           |           |
| planning      |           |           |           |           |
| process look  |           |           |           |           |
| like and what |           |           |           |           |
| does your     |           |           |           |           |
| ongoing block |           |           |           |           |
| hazard        |           |           |           |           |
| assessment    |           |           |           |           |
| process look  |           |           |           |           |
| like?         |           |           |           |           |
| documentation |           |           |           |           |
| required      |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| When do you   |           |           |           |           |
| intend to     |           |           |           |           |
| start         |           |           |           |           |
| operations in |           |           |           |           |
| the following |           |           |           |           |
| blocks?       |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What does     |           |           |           |           |
| your pre-work |           |           |           |           |
| meeting look  |           |           |           |           |
| like, does it |           |           |           |           |
| include all   |           |           |           |           |
| subs -- are   |           |           |           |           |
| potential     |           |           |           |           |
| hazards       |           |           |           |           |
| identified    |           |           |           |           |
| prior to      |           |           |           |           |
| activities    |           |           |           |           |
| occurring?    |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What does the |           |           |           |           |
| firm's        |           |           |           |           |
| orientation   |           |           |           |           |
| process look  |           |           |           |           |
| like for new  |           |           |           |           |
| workers/      |           |           |           |           |
| contractors / |           |           |           |           |
| s             |           |           |           |           |
| ubcontractors |           |           |           |           |
| including     |           |           |           |           |
| service       |           |           |           |           |
| providers     |           |           |           |           |
| arriving at   |           |           |           |           |
| the worksite? |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| Defined Area  |           |           |           |           |
| Safety        |           |           |           |           |
| Orientation   |           |           |           |           |
| reviewed with |           |           |           |           |
| all           |           |           |           |           |
| contractors / |           |           |           |           |
| s             |           |           |           |           |
| ubcontractors |           |           |           |           |
| at the        |           |           |           |           |
| Defined       |           |           |           |           |
| Workplace     |           |           |           |           |
| prior to      |           |           |           |           |
| commencing    |           |           |           |           |
| work          |           |           |           |           |
| activities.   |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| Do all        |           |           |           |           |
| contractors / |           |           |           |           |
| su            |           |           |           |           |
| bcontractors, |           |           |           |           |
| in the        |           |           |           |           |
| workplace     |           |           |           |           |
| provide a     |           |           |           |           |
| list of their |           |           |           |           |
| designated    |           |           |           |           |
| supervisors?  |           |           |           |           |
| documentation |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| How does the  |           |           |           |           |
| operation     |           |           |           |           |
| coordinate    |           |           |           |           |
| the           |           |           |           |           |
| activities of |           |           |           |           |
| all permitted |           |           |           |           |
| persons       |           |           |           |           |
| including     |           |           |           |           |
| contractors / |           |           |           |           |
| s             |           |           |           |           |
| ubcontractors |           |           |           |           |
| at the        |           |           |           |           |
| workplace to  |           |           |           |           |
| ensure the    |           |           |           |           |
| Health and    |           |           |           |           |
| Safety of all |           |           |           |           |
| workers is    |           |           |           |           |
| maintained?   |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What are your |           |           |           |           |
| procedures in |           |           |           |           |
| the workplace |           |           |           |           |
| to ensure     |           |           |           |           |
| safe access?  |           |           |           |           |
| documentation |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What is the   |           |           |           |           |
| process for   |           |           |           |           |
| assessing the |           |           |           |           |
| workplace     |           |           |           |           |
| first aid     |           |           |           |           |
| needs?        |           |           |           |           |
| documentation |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| How are you   |           |           |           |           |
| conducting    |           |           |           |           |
| regular       |           |           |           |           |
| inspections   |           |           |           |           |
| of the        |           |           |           |           |
| Workplace,    |           |           |           |           |
| work methods  |           |           |           |           |
| & practices,  |           |           |           |           |
| including     |           |           |           |           |
| worker        |           |           |           |           |
| inspections?  |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| OHS site      |           |           |           |           |
| safety plan   |           |           |           |           |
| is in place   |           |           |           |           |
| and available |           |           |           |           |
| to all        |           |           |           |           |
| persons.      |           |           |           |           |
| contractors   |           |           |           |           |
| and           |           |           |           |           |
| s             |           |           |           |           |
| ubcontractors |           |           |           |           |
| at the        |           |           |           |           |
| worksite.     |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What is your  |           |           |           |           |
| safety        |           |           |           |           |
| meeting       |           |           |           |           |
| process? Are  |           |           |           |           |
| all persons / |           |           |           |           |
| contractors / |           |           |           |           |
| s             |           |           |           |           |
| ubcontractors |           |           |           |           |
| at the        |           |           |           |           |
| workplace     |           |           |           |           |
| included in   |           |           |           |           |
| the your OHS  |           |           |           |           |
| program and   |           |           |           |           |
| safety        |           |           |           |           |
| meetings?     |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| Are all       |           |           |           |           |
| safety        |           |           |           |           |
| incidents     |           |           |           |           |
| reported and  |           |           |           |           |
| investigated? |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What does     |           |           |           |           |
| your hazard   |           |           |           |           |
| reporting and |           |           |           |           |
| follow up     |           |           |           |           |
| process look  |           |           |           |           |
| like?         |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| What does     |           |           |           |           |
| your ERP look |           |           |           |           |
| like and how  |           |           |           |           |
| was it        |           |           |           |           |
| communicated  |           |           |           |           |
| when it was   |           |           |           |           |
| last tested?  |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| Do you have   |           |           |           |           |
| safe work     |           |           |           |           |
| procedures    |           |           |           |           |
| for all       |           |           |           |           |
| activities    |           |           |           |           |
| being carried |           |           |           |           |
| out?          |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
|               |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| **Signed off  |           |           |           |           |
| on behalf of  |           |           |           |           |
| Company:**    |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| **Signed off  |           |           |           |           |
| by the        |           |           |           |           |
| Contractor:** |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+
| **Dated:**    |           |           |           |           |
+---------------+-----------+-----------+-----------+-----------+


SEND A COPY OF THIS REPORT TO THE PARTY YOU REPORT TO.
 


 

